# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposite', '0019_projectcoeditors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='task_category',
            field=models.CharField(blank=True, choices=[(b'0_preparing', b'Preparing for the Project'), (b'1_launching', b'Launching the Project'), (b'2_managing', b'Managing the Project'), (b'3_assessment', b'Assessment'), (b'4_none', b'')], max_length=48, null=True),
        ),
    ]
