# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposite', '0026_repopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprototype',
            name='driving_question',
            field=models.TextField(default='Not specified.'),
            preserve_default=False,
        ),
    ]
