# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposite', '0028_auto_20170731_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='task_focus',
            field=models.CharField(blank=True, choices=[(b'content', b'Content'), (b'grammar', b'Grammar'), (b'interaction', b'Interaction'), (b'technology', b'Technology'), (b'feedback and/or revision', b'Feedback and/or revision'), (b'reflection', b'Reflection')], max_length=48),
        ),
    ]
