# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposite', '0032_auto_20170802_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='implementationfile',
            old_name='implementation_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='projectfile',
            old_name='project_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='taskfile',
            old_name='task_file',
            new_name='file',
        ),
    ]
