# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposite', '0033_auto_20170802_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='task_category',
            field=models.CharField(choices=[(b'0_preparing', b'Preparing for the Project'), (b'1_launching', b'Launching the Project'), (b'2_managing', b'Managing the Project'), (b'3_assessment', b'Assessment')], max_length=48, null=True),
        ),
    ]
